[functions]
  directory = "netlify/functions"

 [[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Content-Type = "application/json"

  [build]
  command = "npm run build"
  publish = "dist"
